# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Meredith Smith'
tagline:          'My Blog'
description:      
url:              http://lanyon.getpoole.com

author:
  name:           'Meredith Smith'
  url:            

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
  
  baseurl: /lanyon
